name: Docker build test
on: workflow_dispatch

permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - uses: docker/build-push-action@v6.6.0
        with:
          context: .
          push: true
          tags: hitsumabushi845/test-gha:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
