name: Docker build test
on: workflow_dispatch

permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ECR_ENDPOINT }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID}}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
      - uses: docker/build-push-action@v6.6.0
        with:
          context: .
          push: true
          tags: ${{ secrets.ECR_ENDPOINT }}/test-gha:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
